version: '3.8'
services:
  mongo:
    image: mongo:5
    container_name: nest-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/nest?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo_data:
